### ISSUE TITLE
Bottle QGIS 3.6.2

### ISSUE THREAD

**Issue by palmerj** [OSGeo/homebrew-osgeo4mac#1093]
Please!

```
url "https://github.com/qgis/QGIS/archive/final-3_6_2.tar.gz"
sha256 "10920eaac37ea5986a9f833a2db79ec5d5c359edfc6821643a24cfc68df48638"
```

**Comment by fjperini** [comment]
@palmerj today I will update qgis!

**Comment by palmerj** [comment]
Thanks @fjperini. As a side do you know why I can't build QGIS from source. I get the following error:

```
Last 15 lines from /Users/jpalmer/Library/Logs/Homebrew/osgeo-qgis/06.cmake:
  File "/tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/python/qgis/gui/__init__.py", line 27, in <module>
    from qgis._gui import *
RuntimeError: qgis._gui cannot import type 'QVariantMap' from PyQt5.QtCore
[5426/5442] cd /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/python/plugins/db_manager && /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/scripts/pyuic-wrapper.sh /usr/local/Cellar/osgeo-qgis/3.6.2_1/libexec/vendor/bin/pyuic5 /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/lib /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/python /usr/local/opt/python/bin/python3.7 /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/python/plugins/db_manager/ui/DlgCreateConstraint.ui -o /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/python/plugins/db_manager/ui_DlgCreateConstraint.py
FAILED: python/plugins/db_manager/ui_DlgCreateConstraint.py
cd /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/python/plugins/db_manager && /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/scripts/pyuic-wrapper.sh /usr/local/Cellar/osgeo-qgis/3.6.2_1/libexec/vendor/bin/pyuic5 /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/lib /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/python /usr/local/opt/python/bin/python3.7 /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/python/plugins/db_manager/ui/DlgCreateConstraint.ui -o /tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/python/plugins/db_manager/ui_DlgCreateConstraint.py
Traceback (most recent call last):
  File "/tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/scripts/pyuic-wrapper.py", line 26, in <module>
    import qgis.PyQt.uic.pyuic
  File "/tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/python/qgis/__init__.py", line 80, in <module>
    import qgis.gui
  File "/tmp/osgeo-qgis-20190425-12806-15xktt3/QGIS-final-3_6_2/build/output/python/qgis/gui/__init__.py", line 27, in <module>
    from qgis._gui import *
RuntimeError: qgis._gui cannot import type 'QVariantMap' from PyQt5.QtCore
ninja: build stopped: subcommand failed.
```
I have followed the followed steps:
```bash
brew unlink python && brew link --force python
$PATH (Check that there is no other version)
brew reinstall ninja gsl python qt osgeo-sip osgeo-pyqt osgeo-pyqt-webkit osgeo-qscintilla2 six bison flex pkg-config
brew link --overwrite osgeo-pyqt
rm -rf $(brew --cache)
```

And still no luck.

**Comment by fjperini** [comment]
@palmerj Let's check in CI #1095
