### ISSUE TITLE
Some errors during upgrade and can't build osgeo-qgis-ltr

### ISSUE THREAD

**Issue by Emic37** [OSGeo/homebrew-osgeo4mac#1103]
Today, homebrew encountered some errors during upgrading my outdated formulae.

First, with osgeo-postgresql : 
```
==> Installing osgeo/osgeo4mac/osgeo-postgresql
==> Downloading https://bottle.download.osgeo.org/osgeo-postgresql-11.2_2.high_s

curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "osgeo-postgresql"
Download failed: https://bottle.download.osgeo.org/osgeo-postgresql-11.2_2.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```
 Then with osgeo-qgis-res : 
```
==> Installing osgeo/osgeo4mac/osgeo-qgis-res
==> Downloading https://bottle.download.osgeo.org/osgeo-qgis-res-3.6.2_1.high_si

curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "osgeo-qgis-res"
Download failed: https://bottle.download.osgeo.org/osgeo-qgis-res-3.6.2_1.high_sierra.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.

```
Finally, update of osgeo-qgis-ltr fails : 

```
osgeo/osgeo4mac/osgeo-qgis-ltr 3.4.6_1 -> 3.4.7_3
==> Upgrading osgeo/osgeo4mac/osgeo-qgis-ltr 
==> Downloading https://bottle.download.osgeo.org/osgeo-qgis-ltr-3.4.7_3.high_si

curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "osgeo-qgis-ltr"
Download failed: https://bottle.download.osgeo.org/osgeo-qgis-ltr-3.4.7_3.high_sierra.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/qgis/QGIS/archive/final-3_4_7.tar.gz
Already downloaded: /Users/Aymeric/Library/Caches/Homebrew/downloads/b4a654318205abb2b046931fd8fddbd6178eec43f7ef4899f87d9e64952e8122--QGIS-final-3_4_7.tar.gz
==> Patching
patching file cmake/FindQsci.cmake
patching file cmake/FindPyQt5.py
patching file cmake/FindPyQt5.cmake
patching file src/app/qgisapp.cpp
Hunk #1 succeeded at 496 (offset -13 lines).
patching file src/ui/qgsabout.ui
==> Downloading https://bottle.download.osgeo.org/qgis-splash/splash-3.4.png
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "osgeo-qgis-ltr--splash"
Download failed: https://bottle.download.osgeo.org/qgis-splash/splash-3.4.png
```

**Comment by fjperini** [comment]
@Emic37 Thanks for reporting this, we will resolve it.

**Comment by fjperini** [comment]
solved!

**Comment by Emic37** [comment]
Ok thank you very much !

**Comment by fjperini** [comment]
@Emic37 it may be necessary to update `osgeo-qgis-ltr` for the new update of `osgeo-sip`

**Comment by Emic37** [comment]
Ok thanks ! For information, I have same problem with `osgeo-qgis`.

**Comment by Emic37** [comment]
Sorry but I tried to upgrade `osgeo-qgis-ltr` to `3.4.7_4` but it still failed : 
```
[3404/5276] cd /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E echo && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E touch /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart0.cpp /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart1.cpp /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart2.cpp /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart3.cpp && /usr/local/Cellar/osgeo-sip/4.19.16/bin/sip -w -e -x TESTS -x ANDROID -x ARM -x MOBILITY_LOCATION -n PyQt5.sip -t WS_MACX -t Qt_5_12_1 -g -o -a /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/qgis.server.api -n PyQt5.sip -y /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/output/python/qgis/_server.pyi -j 4 -c /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server -I /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server -I /usr/local/share/sip/PyQt5 -I /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/python /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/server.sip

ninja: build stopped: subcommand failed.
```

**Comment by Emic37** [comment]
Sorry, maybe I don't understand but I tried to update `osgeo-qgis-ltr` and it still failed : 

```
[3404/5276] cd /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E echo && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E touch /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart0.cpp /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart1.cpp /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart2.cpp /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/sip_serverpart3.cpp && /usr/local/Cellar/osgeo-sip/4.19.16/bin/sip -w -e -x TESTS -x ANDROID -x ARM -x MOBILITY_LOCATION -n PyQt5.sip -t WS_MACX -t Qt_5_12_1 -g -o -a /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/qgis.server.api -n PyQt5.sip -y /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/output/python/qgis/_server.pyi -j 4 -c /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server -I /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server -I /usr/local/share/sip/PyQt5 -I /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/python /tmp/osgeo-qgis-ltr-20190507-78930-zhd2k3/QGIS-final-3_4_7/build/python/server/server.sip

ninja: build stopped: subcommand failed.
```

**Comment by Chrismarsh** [comment]
I'm also seeing the PyQt5 sip error. Do we just hang tight for your patch @Emic37 ?

**Comment by mdmadhu** [comment]
+1

> I'm also seeing the PyQt5 sip error. Do we just hang tight for your patch @Emic37 ?

**Comment by fjperini** [comment]
tomorrow I will sit down to solve everything!

Do not despair, we will solve it.

**Comment by GuiAlDuS** [comment]
I'm also having a similar issue with SIP module:

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/__init__.py", line 72, in 
    from qgis.PyQt import QtCore
  File "/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/qgis/PyQt/QtCore.py", line 26, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'


Python version:
3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]

QGIS version:
3.6.2-Noosa 'Noosa', exported

Python path:
['/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python', '/Users/guillermoduran/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/guillermoduran/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/usr/local/opt/osgeo-qgis/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/usr/local/opt/osgeo-gdal-python/lib/python3.7/site-packages', '/usr/local/opt/osgeo-qgis/QGIS.app/Contents/Resources/python', '/usr/local/opt/osgeo-qgis/lib/python3.7/site-packages', '/usr/local/opt/lib/python3.7/site-packages', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geos', '/usr/local/Cellar/osgeo-matplotlib/3.0.3_1/libexec/lib/python3.7/site-packages', '/usr/local/Cellar/numpy/1.16.3_1/libexec/nose/lib/python3.7/site-packages', '/usr/local/Cellar/protobuf/3.7.1/libexec/lib/python3.7/site-packages']
```

**Comment by fjperini** [comment]
@Emic37 @Chrismarsh @mdmadhu already updating everything, first I need to make some corrections in other formulas.

**Comment by fjperini** [comment]
Creating the bottle. We close this issue.
