### ISSUE TITLE
invalid syntax in tap!

### ISSUE THREAD

**Issue by PaoloC68** [OSGeo/homebrew-osgeo4mac#175]
When I tap osgeo4mac I got this below.
Especially what can I do with this: `Error: Cannot tap osgeo/osgeo4mac: invalid syntax in tap!` ?
I am on `10.11.6`.
```
brew tap osgeo/osgeo4mac
==> Tapping osgeo/osgeo4mac
Cloning into '/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac'...
remote: Counting objects: 95, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 95 (delta 13), reused 21 (delta 0), pack-reused 0
Unpacking objects: 100% (95/95), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:31:in `<class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:31:in `<class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:31:in `<class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:35:in `block in <class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling 'depends_on :freetype' is deprecated!
Use 'depends_on "freetype"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:58:in `<class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling 'depends_on :libpng' is deprecated!
Use 'depends_on "libpng"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:59:in `<class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:80:in `block in <class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:80:in `block in <class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mapserver-64.rb:80:in `block in <class:Mapserver64>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/marble.rb:4:in `<class:Marble>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/marble.rb:4:in `<class:Marble>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/marble.rb:4:in `<class:Marble>'
Please report this to the osgeo/osgeo4mac tap!

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb
No available formula with the name "orfeo-42"
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/nitro.rb:6:in `<class:Nitro>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/nitro.rb:6:in `<class:Nitro>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/nitro.rb:6:in `<class:Nitro>'
Please report this to the osgeo/osgeo4mac tap!

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb
No available formula with the name "orfeo-42"
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osm2po.rb:11:in `<class:Osm2po>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osm2po.rb:11:in `<class:Osm2po>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osm2po.rb:11:in `<class:Osm2po>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pointcloud.rb:7:in `<class:Pointcloud>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pointcloud.rb:7:in `<class:Pointcloud>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pointcloud.rb:7:in `<class:Pointcloud>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/prepair.rb:5:in `<class:Prepair>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/prepair.rb:5:in `<class:Prepair>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/prepair.rb:5:in `<class:Prepair>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:4:in `<class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:4:in `<class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:4:in `<class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:9:in `block in <class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:20:in `block in <class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:20:in `block in <class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/taudem.rb:20:in `block in <class:Taudem>'
Please report this to the osgeo/osgeo4mac tap!

Error: Cannot tap osgeo/osgeo4mac: invalid syntax in tap!
```

**Comment by mattayes** [comment]
☝️ Same issue.
```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:9:in `<class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:9:in `<class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:9:in `<class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:13:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:27:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:27:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:27:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:33:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:33:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:33:in `block in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/monteverdi2.rb:41:in `block (2 levels) in <class:Monteverdi2>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:12:in `<class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:12:in `<class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:12:in `<class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/orfeo-ice.rb:16:in `block in <class:OrfeoIce>'
Please report this to the osgeo/osgeo4mac tap!
```

**Comment by dakcarto** [comment]
@PaoloC68 an @mattayes please try again. Thanks. I've updated many formulae to account for this error.

**Comment by PaoloC68** [comment]
Thanks, the fix worked

**Comment by jannefleischer** [comment]
Hm. There are invalid formulas once again:

> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/mrsid-sdk.rb
> invalid attribute for formula 'osgeo/osgeo4mac/mrsid-sdk': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/MrSID_DSDK-9.5.1.4427-darwin14.universal.clang60.tar.gz")
> 
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/oracle-client-sdk.rb
> invalid attribute for formula 'osgeo/osgeo4mac/oracle-client-sdk': url ("file:///Volumes/1000er Intern/Users/Janne/Library/Caches/Homebrew/instantclient-basiclite-macos.x64-12.1.0.2.0.zip")
> 
> Error: Cannot tap osgeo/osgeo4mac: invalid syntax in tap!
