### ISSUE TITLE
Python error: Couldn't load plugin MetaSearch due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by chrismarx** [OSGeo/homebrew-osgeo4mac#199]
Hi,

Just tried building QGIS and the build completes, but upon opening the app, I get the above message. 

```
$ brew doctor
 Your system is ready to brew. 
 $ brew tap osgeo/osgeo4mac
 $ brew install qgis2 --with-oracle
 $ brew linkapps qgis2
 $ sudo pip install psycopg2
 $ sudo pip install future
```

Running :

sudo pip install requests

fixed the problem, but that package was not listed in the post install messages. This is what I did see:

The following Python modules are needed by QGIS during run-time:

    psycopg2, future

You can install manually, via installer package or with `pip` (if availble):

    pip install <module>  OR  pip-2.7 install <module>

**Comment by dakcarto** [comment]
Hi. What was the actual error?

**Comment by chrismarx** [comment]
That was pretty much the full error in the title, it was:

"Python error: Couldn't load plugin MetaSearch due to an error when calling its classFactory() method See message log (Python Error) for more details."

Showed up as a yellow error bar at the top of the map view

**Comment by dakcarto** [comment]
> See message log (Python Error) for more details.

I meant that error stack trace. Thanks.

**Comment by chrismarx** [comment]
Ok,

I uninstalled the requests package, and then I could see the error again:

Couldn't load plugin MetaSearch due to an error when calling its classFactory() method 

ImportError: No module named requests 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/plugin.py", line 33, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/dialogs/maindialog.py", line 43, in 
    from owslib.csw import CatalogueServiceWeb
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/owslib/csw.py", line 27, in 
    from owslib.util import OrderedDict
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/owslib/util.py", line 35, in 
    import requests
  File "/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named requests


Python version: 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
QGIS version: 2.18.2 Las Palmas, exported 

Python Path:
/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python
/Users/***removed***/.qgis2/python
/Users/***remved***/.qgis2/python/plugins
/usr/local/Cellar/qgis2/2.18.2/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg
/usr/local/opt/gdal2-python/lib/python2.7/site-packages
/usr/local/lib/qt-4/python2.7/site-packages
/usr/local/opt/qgis2/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/**removed***/.qgis2//python

**Comment by dakcarto** [comment]
@chrismarx ok, thanks!

Added `requests` to Caveats in ea0397c. Please reopen if necessary.

**Comment by orkutmuratyilmaz** [comment]
I reopen this issue, with the QGIS 3.16.0 Hannover.

We use Pop!_OS (Ubuntu 20.04 Derivative). Full error message is:

```
Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pygments' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/app/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 61, in 
    from MetaSearch.dialogs.manageconnectionsdialog import ManageConnectionsDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/dialogs/manageconnectionsdialog.py", line 35, in 
    from MetaSearch.util import (get_connections_from_file, get_ui_class,
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/util.py", line 40, in 
    from pygments import highlight
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pygments'


Python version: 3.8.6 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
QGIS version: 3.16.0-Hannover Hannover, 43b64b13 

Python Path:
/app/share/qgis/python
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/form
```s
