### ISSUE TITLE
Couldn't load plugin 'processing'

### ISSUE THREAD

**Issue by renkeji** [OSGeo/homebrew-osgeo4mac#264]
Installed the latest qgis2.18.11_1, when launching the app, seeing the errors:
```
Python error: Couldn't load plugin 'processing' See message log (Python Error) for more details.
Python error: Couldn't load plugin MetaSearch due to an error when calling its classFactory() method See message log (Python Error) for more details.
```
```
2017-08-15T12:18:32	1	Traceback (most recent call last):
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
			    from MetaSearch.plugin import MetaSearchPlugin
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/plugin.py", line 33, in <module>
			    from MetaSearch.dialogs.maindialog import MetaSearchDialog
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/dialogs/maindialog.py", line 48, in <module>
			    from MetaSearch.dialogs.manageconnectionsdialog import ManageConnectionsDialog
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/dialogs/manageconnectionsdialog.py", line 35, in <module>
			    from MetaSearch.util import (get_connections_from_file, get_ui_class,
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/util.py", line 45, in <module>
			    from qgis.PyQt.uic import loadUiType
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/PyQt/uic/__init__.py", line 26, in <module>
			    from PyQt4.uic.Compiler import indenter, compiler
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named uic.Compiler
			
2017-08-15T12:18:32	1	Traceback (most recent call last):
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 308, in loadPlugin
			    __import__(packageName)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/tools/general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/core/Processing.py", line 42, in <module>
			    from processing.script.ScriptUtils import ScriptUtils
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/script/ScriptUtils.py", line 30, in <module>
			    from processing.script.ScriptAlgorithm import ScriptAlgorithm
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/script/ScriptAlgorithm.py", line 34, in <module>
			    from processing.gui.Help2Html import getHtmlFromHelpFile
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/__init__.py", line 1, in <module>
			    from qgis.PyQt import uic
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/PyQt/uic/__init__.py", line 26, in <module>
			    from PyQt4.uic.Compiler import indenter, compiler
			  File "/usr/local/Cellar/qgis2/2.18.11_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named uic.Compiler
```

**Comment by dakcarto** [comment]
Hi @renkeji, thanks for reporting!

How are you launching the QGIS application?

**Comment by dakcarto** [comment]
See [this comment](https://github.com/OSGeo/homebrew-osgeo4mac/issues/258#issuecomment-322248802) about fixing anything reported by `brew doctor`.

**Comment by dakcarto** [comment]
Btw: `find /usr/local -name "QGIS.app"` could give you unwanted results.

Best to use `brew linkapps qgis2`, as indicated in `brew info qgis2` output. See also `man brew`.

**Comment by renkeji** [comment]
@dakcarto Thanks so much, problem solved!

**Comment by renkeji** [comment]
@dakcarto ```brew linkapps``` is deprecated?

**Comment by dakcarto** [comment]
Cool! Closing issue. What solved it?

> brew linkapps is deprecated?

Could be. Haven't run it recently.

**Comment by renkeji** [comment]
I just needed to brew link the followings:
```
pyqt-qt4
qscintilla2-qt4
sip-qt4
```

**Comment by xigrug** [comment]
same question but in LINUX, how to fix it
