### ISSUE TITLE
Python error on 2.18.14 on 10.9

### ISSUE THREAD

**Issue by cbertelli** [OSGeo/homebrew-osgeo4mac#467]
Hello,
I couldn't upgrade to subsequent versions for issues on clang, but I had other programs on brew that had to be upgraded.
This is what I found today:

```
Couldn't load QGIS utils.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 20, in 
    from future import standard_library
  File "/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python/future/standard_library/__init__.py", line 65, in 
    import logging
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in 
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in 
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref


Python version:
2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]

QGIS version:
2.18.14 'Las Palmas', exported

Python path:
['/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/carlo/.qgis2/python', u'/Users/carlo/.qgis2/python/plugins', '/usr/local/Cellar/qgis2/2.18.14/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/usr/local/lib/python2.7/site-packages/kartograph.py-0.6.8-py2.7.egg', '/usr/local/lib/python2.7/site-packages/kartograph.py-0.6.8-py2.7.egg', '/usr/local/opt/gdal2-python/lib/python2.7/site-packages', '/usr/local/lib/qt-4/python2.7/site-packages', '/usr/local/opt/qgis2/libexec/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/carlo/Library/Python/2.7/lib/python/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/usr/local/lib/python2.7/site-packages/geos', '/usr/local/Cellar/matplotlib/2.0.2/libexec/lib/python2.7/site-packages', '/usr/local/Cellar/numpy/1.14.4/libexec/nose/lib/python2.7/site-packages', '/usr/local/Cellar/protobuf/3.3.2/libexec/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0', '/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/usr/local/lib/python2.7/site-packages/geos', '/usr/local/Cellar/matplotlib/2.0.2/libexec/lib/python2.7/site-packages', '/usr/local/Cellar/numpy/1.14.4/libexec/nose/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0', '/usr/local/lib/python2.7/site-packages/gtk-2.0', '/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa']
```

Is there something I could do?

**Comment by cbertelli** [comment]
I solved it myself. Even if not with a good solution:
brew switch python 2.7.14
because python is now version 3 and what used to be python is now python@2. The following versions of qgis2 take care of this change. Unfortunately I couldn't get them. Brew is not for old systems.

**Comment by fjperini** [comment]
@cbertelli @nickrobison You can close this issue!
