### ISSUE TITLE
Cant load processing plugin: Numpy `nan_to_num`

### ISSUE THREAD

**Issue by peteWT** [OSGeo/homebrew-osgeo4mac#514]
Processing plugin can't load due to a `classFactory()` error:

Couldn't load plugin 'processing' due to an error when calling its classFactory() method 

	ImportError: cannot import name 'nan_to_num' from 'numpy' (unknown location) 
	Traceback (most recent call last):
 	 File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in 	startPlugin
    	plugins[packageName] = package.classFactory(iface)
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/__init__.py", line 36, in classFactory
	    from processing.ProcessingPlugin import ProcessingPlugin
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
	    mod = _builtin_import(name, globals, locals, fromlist, level)
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/ProcessingPlugin.py", line 50, in 
	    from processing.gui.HistoryDialog import HistoryDialog
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
	    mod = _builtin_import(name, globals, locals, fromlist, level)
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/HistoryDialog.py", line 37, in 
	    from processing.gui import TestTools
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
	    mod = _builtin_import(name, globals, locals, fromlist, level)
	  File "/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/TestTools.py", line 38, in 
	    from numpy import nan_to_num
	ImportError: cannot import name 'nan_to_num' from 'numpy' (unknown location)
	
	
	Python version: 3.7.0 (default, Aug 22 2018, 15:22:33) [Clang 9.1.0 (clang-902.0.39.2)] 
	QGIS version: 3.4.0-Madeira Madeira, exported 
	
	Python Path:
	/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python
	/Users/pete/Library/Application Support/QGIS/QGIS3/profiles/default/python
	/Users/pete/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
	/usr/local/Cellar/qgis3/3.4.0/QGIS.app/Contents/MacOS/../Resources/python/plugins
	/usr/local/opt/gdal2-python/lib/python3.7/site-packages
	/usr/local/opt/qgis3/lib/python3.7/site-packages
	/usr/local/opt/qgis3/libexec/vendor/lib/python3.7/site-packages
	/usr/local/Cellar/qgis3/3.4.0/libexec/vendor/lib/python3.7/site-packages
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
	/usr/local/Cellar/matplotlib/2.2.3/libexec/lib/python3.7/site-packages
	/Users/pete/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by fjperini** [comment]
@peteWT Test with the changes applied #514

**Comment by peteWT** [comment]
@fjperini @nickrobison 

Confirming this issue is resolved with `$> brew reinstall qgis3 --with-grass`
