### ISSUE TITLE
Grass7 processing plugin fails to activate in QGIS

### ISSUE THREAD

**Issue by jonathanmccormack** [OSGeo/homebrew-osgeo4mac#519]
This appears to be an upstream problem (so I've [submitted](https://issues.qgis.org/issues/20342) to the QGIS bug tracker) but for completeness I am also submitting here.

When I launch QGIS 3.4.1 (and 3.4.0 before it), I get the following error upon startup:
```
Couldn't load plugin 'processing' due to an error when calling its initGui() method 

AttributeError: type object 'Grass7Utils' has no attribute 'checkGrass7IsInstalled' 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/ProcessingPlugin.py", line 181, in initGui
    self.toolbox = ProcessingToolbox()
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/ProcessingToolbox.py", line 93, in __init__
    self.txtTip.setVisible(self.disabledProviders())
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/ProcessingToolbox.py", line 135, in disabledProviders
    if not provider.isActive() and provider.canBeActivated():
  File "/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py", line 157, in canBeActivated
    return not bool(Grass7Utils.checkGrass7IsInstalled())
AttributeError: type object 'Grass7Utils' has no attribute 'checkGrass7IsInstalled'


Python version: 3.7.0 (default, Jul 23 2018, 20:22:55) [Clang 9.1.0 (clang-902.0.39.2)] 
QGIS version: 3.4.1-Madeira Madeira, exported 

Python Path:
/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python
/Users/jonathan.mccormack/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jonathan.mccormack/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/Cellar/qgis3/3.4.1/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/gdal2-python/lib/python3.7/site-packages
/usr/local/opt/qgis3/lib/python3.7/site-packages
/usr/local/opt/qgis3/libexec/vendor/lib/python3.7/site-packages
/usr/local/Cellar/qgis3/3.4.1/libexec/vendor/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
/usr/local/Cellar/matplotlib/2.2.3/libexec/lib/python3.7/site-packages
/Users/jonathan.mccormack/Library/Application Support/QGIS/QGIS3/profiles/default/python
```
There appears to be an outdated reference to the method 'checkGrass7IsInstalled' in the file [python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py](https://github.com/qgis/QGIS/blob/e9deafcf3742e767c69d7bc4ec71e18ff57b4823/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py#L157).  The method was renamed from 'checkGrass7IsInstalled' to 'checkGrassIsInstalled' in the file [python/plugins/processing/algs/grass7/Grass7Utils.py](https://github.com/qgis/QGIS/blob/e9deafcf3742e767c69d7bc4ec71e18ff57b4823/python/plugins/processing/algs/grass7/Grass7Utils.py#L459) as part of commit qgis/QGIS@6c81895fb0701236c10694a257756e47aacdb493

I have no idea why this problem is only occurring now, when the problematic line has been there for a year, and as I said, I'm pretty sure this is an upstream problem.  For the time being, I can resolve this by manually fixing the line in Grass7AlgorithmProvider.py, but those changes are lost every time I upgrade QGIS.

**Comment by fjperini** [comment]
@jonathanmccormack Is this error still present?
If you can check it, to confirm that it is solved.
