### ISSUE TITLE
Problems with OTB plugin in QGIS3 

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#587]
App crashes when I try to activate / tick the plugin in the QGIS interface. Perhaps related to #582 

if I tick the OTB plugin in plugins, qgis3 crashes, the next time this error appears and I can't untick anymore because every time I try the app crashes. 🎉 😅 

```
Couldn't load plugin 'otb' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'otb.OtbAlgorithmProvider' 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python/plugins/otb/__init__.py", line 37, in classFactory
    from .OTBPlugin import OTBPlugin
  File "/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python/plugins/otb/OTBPlugin.py", line 26, in 
    from .OtbAlgorithmProvider import OtbAlgorithmProvider
  File "/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'otb.OtbAlgorithmProvider'


Python version: 3.7.2 (default, Jan 12 2019, 20:39:48) [Clang 10.0.0 (clang-1000.11.45.5)] 
QGIS version: 3.4.3-Madeira Madeira, 5364afe4 

Python Path:
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/extlibs
/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/Cellar/qgis3/3.4.3_2/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/gdal2-python/lib/python3.7/site-packages
/usr/local/opt/qgis3/lib/python3.7/site-packages
/usr/local/opt/qgis3/libexec/vendor/lib/python3.7/site-packages
/usr/local/Cellar/qgis3/3.4.3_2/libexec/vendor/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geos
/usr/local/Cellar/matplotlib/2.2.3/libexec/lib/python3.7/site-packages
/usr/local/Cellar/numpy/1.15.4_2/libexec/nose/lib/python3.7/site-packages
/Users/lpuerto/Library/Application Support/QGIS/QGIS3/profiles/default/python
```
![screen shot 2019-01-14 at 12 24 10](https://user-images.githubusercontent.com/22882880/51107518-b276c580-17f7-11e9-98f6-5e3173a0b955.png)

PS/ continue the conversation from [here](https://github.com/OSGeo/homebrew-osgeo4mac/issues/583#issuecomment-453908401).

**Comment by luispuerto** [comment]
I think I going to build the QGIS3 again but without orfeo, the problem is even if I build without orfeo I've seen the plugin there...

**Comment by fjperini** [comment]
I will download the obb files and create the patches again.
p/d: to drop some things, delete the Homebrew cache.

**Comment by luispuerto** [comment]
So... to be clear... I've deleted the brew cache (`rm -rf $(brew --cache)`), should I do anything else before I rebuild? I'm thinking to merge #450, #584, #585 & #586 and then build 🏗  again.

**Comment by fjperini** [comment]
@luispuerto I found the problem It was the name of the file.

OTBUtils.py  it must be changed to OtbUtils.py, in the same way for OTBAlgorithmProvider.

**Comment by luispuerto** [comment]
Great! Do you need to make a pull?

**Comment by luispuerto** [comment]
Ok... I see that now works...

**Comment by fjperini** [comment]
Yes, I verify that it builds and I applies the changes.

**Comment by fjperini** [comment]
I am not presented with this error #582
let's see if with the last commit this is solved.

**Comment by luispuerto** [comment]
Ok... so let's keep #582 out of this since it's a marginal error, at least at the moment. 

I can fetch your pull request tonight (EET) and rebuild 🏗 I'm sure that now it's going to work.

**Comment by fjperini** [comment]
I applied the new changes #585

**Comment by fjperini** [comment]
@luispuerto Verified, this was resolved 🎉

**Comment by luispuerto** [comment]
yeah! the same here 👍 😃
