### ISSUE TITLE
qgis install fails on python-dateutil

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#616]
I've got an error when installing qgis with

```
brew install --with-3d --with-gpsbabel --with-grass --with-hdf5 --with-isolation --with-liblas --with-netcdf --with-openvpn --with-oracle --with-pdal --with-qspatialite --with-r --with-saga --with-szip qgis
```

It fails on python-dateutil module installation. 
Seems like it fails on a cleanup phase.

```
==> /usr/local/Cellar/qgis/3.4.4/libexec/vendor/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qgis--pyproj-20190123-59640-1mt6m4z
==> Downloading https://files.pythonhosted.org/packages/0e/01/68747933e8d12263d41ce08119620d9a7e5eb72c876a3442257f74490da0/python-dateutil-2.7.5.tar.gz
Already downloaded: /Users/bezdna/Library/Caches/Homebrew/downloads/c7cf25836e4477bd26d02ff03b8de1bc4cf52b3a73566c3e5585911cab254918--python-dateutil-2.7.5.tar.gz
==> /usr/local/Cellar/qgis/3.4.4/libexec/vendor/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qgis--python-dateutil-20190123-59640-x0edhf/python-dateutil-2.7.5
...

Removed file:///private/tmp/qgis--python-dateutil-20190123-59640-x0edhf/python-dateutil-2.7.5 from build tracker '/private/tmp/pip-req-tracker-asgfdopm'
Removed build tracker '/private/tmp/pip-req-tracker-asgfdopm'
Exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 149, in prep_for_dist
    reqs = self.req.pep517_backend.get_requires_for_build_wheel()
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable
```

**Comment by fjperini** [comment]
@nextstopsun try after removing the homebrew cache and the temporary files of the builds.

**Comment by fjperini** [comment]
@nextstopsun `python-dateutil` it is temporarily disabled until finding a solution.

It seems that there were changes in `pip`.

suggestions?

**Comment by nextstopsun** [comment]
@fjperini Do you know in what parts of qgis is this lib used?

**Comment by nextstopsun** [comment]
Btw had to manually upgrade pip to v19. But no luck either. Maybe pip upgrade should be included in formula recipe

**Comment by chinigo** [comment]
Also getting this error. Happy to provide logs or verify test builds.

```
2019-01-23 16:13:58 -0500

/usr/local/Cellar/qgis/3.4.4/libexec/vendor/bin/pip
install
-v
--no-deps
--no-binary
:all:
--ignore-installed
/private/tmp/qgis--python-dateutil-20190123-23007-1wdgalm/python-dateutil-2.7.5

Created temporary directory: /private/tmp/pip-ephem-wheel-cache-bm5226n4
Created temporary directory: /private/tmp/pip-req-tracker-j6aft2u2
Created requirements tracker '/private/tmp/pip-req-tracker-j6aft2u2'
Created temporary directory: /private/tmp/pip-install-08mdmwuy
Processing /private/tmp/qgis--python-dateutil-20190123-23007-1wdgalm/python-dateutil-2.7.5
  Created temporary directory: /private/tmp/pip-req-build-wysnvhez
  Added file:///private/tmp/qgis--python-dateutil-20190123-23007-1wdgalm/python-dateutil-2.7.5 to build tracker '/private/tmp/pip-req-tracker-j6aft2u2'
  Created temporary directory: /private/tmp/pip-build-env-qrr4mkcs
  Installing build dependencies: started
  Running command /usr/local/Cellar/qgis/3.4.4/libexec/vendor/bin/python3.7 /usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-qrr4mkcs/overlay --no-warn-script-location -v --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.2.0 wheel
  Created temporary directory: /private/tmp/pip-ephem-wheel-cache-b__t5gik
  Re-using requirements tracker '/private/tmp/pip-req-tracker-j6aft2u2'
  Created temporary directory: /private/tmp/pip-install-yh4x2zwr


  <…snip…>


  Successfully installed setuptools-40.6.3 wheel-0.32.3
  Cleaning up...
  Cleaned build tracker '/private/tmp/pip-req-tracker-j6aft2u2'
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command /usr/local/Cellar/qgis/3.4.4/libexec/vendor/bin/python3.7 /usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/tmp/tmp3d2fbljq
  Getting requirements to build wheel: finished with status 'done'
Cleaning up...
  Removing source in /private/tmp/pip-req-build-wysnvhez
Removed file:///private/tmp/qgis--python-dateutil-20190123-23007-1wdgalm/python-dateutil-2.7.5 from build tracker '/private/tmp/pip-req-tracker-j6aft2u2'
Removed build tracker '/private/tmp/pip-req-tracker-j6aft2u2'
Exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 149, in prep_for_dist
    reqs = self.req.pep517_backend.get_requires_for_build_wheel()
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/usr/local/Cellar/qgis/3.4.4/libexec/vendor/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable

HOMEBREW_VERSION: 1.9.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2271acc75c7b3bfc668d7d492fa39bc7266f02fc
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/chinigo/Library/Caches/Homebrew
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.63.0 => /usr/local/opt/curl/bin/curl
Java: 1.8.0_102
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/bison:/usr/local/opt/flex:/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/qt:/usr/local/opt/libffi:/usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/jpeg-turbo:/usr/local/opt/libxml2:/usr/local/opt/libxslt:/usr/local/opt/zlib:/usr/local/opt/qt5-webkit:/usr/local/opt/expat:/usr/local/opt/libpq:/usr/local/opt/curl:/usr/local/opt/libiconv:/usr/local/opt/openblas:/usr/local/opt/gdal2:/usr/local/opt/nss:/usr/local/opt/gdal2-python:/usr/local/opt/lapack:/usr/local/opt/tcl-tk:/usr/local
CMAKE_INCLUDE_PATH: /opt/X11/include:/opt/X11/include/freetype2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /opt/X11/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks:/usr/local/opt/qt/Frameworks:/usr/local/opt/python@2/Frameworks:/usr/local/opt/qt5-webkit/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/gsl/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/python@2/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/gstreamer/lib/pkgconfig:/usr/local/opt/libogg/lib/pkgconfig:/usr/local/opt/libvorbis/lib/pkgconfig:/usr/local/opt/opus/lib/pkgconfig:/usr/local/opt/orc/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/theora/lib/pkgconfig:/usr/local/opt/gst-plugins-base/lib/pkgconfig:/usr/local/opt/jpeg-turbo/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libxslt/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/qt5-webkit/lib/pkgconfig:/usr/local/opt/qca/lib/pkgconfig:/usr/local/opt/qjson/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/spatialindex/lib/pkgconfig:/usr/local/opt/postgresql/lib/pkgconfig:/usr/local/opt/libpq/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libzip/lib/pkgconfig:/usr/local/opt/libtasn1/lib/pkgconfig:/usr/local/opt/freexl/lib/pkgconfig:/usr/local/opt/libspatialite/lib/pkgconfig:/usr/local/opt/json-c/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/mpfr/lib/pkgconfig:/usr/local/opt/openblas/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig:/usr/local/opt/open-mpi/lib/pkgconfig:/usr/local/opt/arpack/lib/pkgconfig:/usr/local/opt/armadillo/lib/pkgconfig:/usr/local/opt/gdal2/lib/pkgconfig:/usr/local/opt/protobuf/lib/pkgconfig:/usr/local/opt/protobuf-c/lib/pkgconfig:/usr/local/opt/little-cms2/lib/pkgconfig:/usr/local/opt/nspr/lib/pkgconfig:/usr/local/opt/nss/lib/pkgconfig:/usr/local/opt/openjpeg/lib/pkgconfig:/usr/local/opt/poppler/lib/pkgconfig:/usr/local/opt/libssh/lib/pkgconfig:/usr/local/opt/exiv2/lib/pkgconfig:/usr/local/opt/lapack/lib/pkgconfig:/usr/local/opt/unixodbc/lib/pkgconfig:/usr/local/opt/fftw/lib/pkgconfig:/usr/local/opt/tcl-tk/lib/pkgconfig:/usr/local/opt/eigen/share/pkgconfig:/usr/local/opt/poppler/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/opt/bison/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/opt/libxslt/share/aclocal:/usr/local/opt/curl/share/aclocal:/usr/local/share/aclocal:/opt/X11/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/cmake/bin:/usr/local/opt/ninja/bin:/usr/local/opt/gsl/bin:/usr/local/opt/sip/bin:/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python/bin:/usr/local/opt/qt/bin:/usr/local/opt/python@2/bin:/usr/local/opt/pyqt/bin:/usr/local/opt/conan/bin:/usr/local/opt/glslang/bin:/usr/local/opt/gettext/bin:/usr/local/opt/pcre/bin:/usr/local/opt/glib/bin:/usr/local/opt/gstreamer/bin:/usr/local/opt/orc/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/cairo/bin:/usr/local/opt/fribidi/bin:/usr/local/opt/graphite2/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/harfbuzz/bin:/usr/local/opt/pango/bin:/usr/local/opt/gst-plugins-base/bin:/usr/local/opt/jpeg-turbo/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/webp/bin:/usr/local/opt/qca/bin:/usr/local/opt/expat/bin:/usr/local/opt/proj/bin:/usr/local/opt/postgresql/bin:/usr/local/opt/libpq/bin:/usr/local/opt/curl/bin:/usr/local/opt/libzip/bin:/usr/local/opt/libtasn1/bin:/usr/local/opt/libiconv/bin:/usr/local/opt/geos/bin:/usr/local/opt/qhull/bin:/usr/local/opt/giflib/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/libgeotiff/bin:/usr/local/opt/gcc/bin:/usr/local/opt/numpy/bin:/usr/local/opt/libevent/bin:/usr/local/opt/open-mpi/bin:/usr/local/opt/hdf5/bin:/usr/local/opt/cgal/bin:/usr/local/opt/sfcgal/bin:/usr/local/opt/gdal2/bin:/usr/local/opt/protobuf/bin:/usr/local/opt/protobuf-c/bin:/usr/local/opt/postgis2/bin:/usr/local/opt/little-cms2/bin:/usr/local/opt/nspr/bin:/usr/local/opt/nss/bin:/usr/local/opt/openjpeg/bin:/usr/local/opt/poppler/bin:/usr/local/opt/gnu-sed/bin:/usr/local/opt/exiv2/bin:/usr/local/opt/gdal2-python/bin:/usr/local/opt/ghostscript/bin:/usr/local/opt/lbzip2/bin:/usr/local/opt/libtool/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/wxmac/bin:/usr/local/opt/fftw/bin:/usr/local/opt/tcl-tk/bin:/usr/local/opt/grass7/bin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by fjperini** [comment]
@nextstopsun @chinigo I'm in this

Recently there were changes in `pip` that led to this error.

Doing some tests to solve this.

**Comment by chinigo** [comment]
Yup, I see the CI builds going by. Godspeed!

(This isn't a critical error for me, by the way, so no pressure.)

**Comment by fjperini** [comment]
I will disable this module temporarily until receive an update.

**Comment by fjperini** [comment]
@nextstopsun I already solve this, I will apply this change together with others during the day.
