### ISSUE TITLE
Post-Install Step Issue (3.6)

### ISSUE THREAD

**Issue by Wicky2k8** [OSGeo/homebrew-osgeo4mac#814]
Installing QGIS 3.6 from the bottle works well, but the post-install step fails. This seems to be because the script is trying to copy files which are already symlinked to in the QGIS .app's pluging folder, but not 100% sure..

```
GRASS 7 GrassUtils.py already updated
ORFEO 6 OTBUtils.py already updated
Whitebox Tools whiteboxProvider.py has been updated
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/open-mpi.rb
TauDEM taudemProvider.py and has been updated
LAStools LAStoolsProvider.py already updated
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/openscenegraph-qt5.rb
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis-res.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall osgeo/osgeo4mac/qgis`
==> An exception occurred within a child process:
  Errno::EPERM: Operation not permitted @ rb_file_s_symlink - (../../../../../../../opt/qgis-res/libexec/vendor/lib/python3.7/site-packages/pycparser-2.19-py3.7.egg-info, /usr/local/Cellar/qgis/3.6.0_4/QGIS.app/Contents/Resources/python/pycparser-2.19-py3.7.egg-info/pycparser-2.19-py3.7.egg-info)

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:359:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:359:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1586:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:357:in `ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:380:in `ln_sf'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:141:in `install_symlink_p'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:128:in `block (2 levels) in install_symlink'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:128:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:128:in `block in install_symlink'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:125:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:125:in `install_symlink'
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/qgis.rb:1092:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1007:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:864:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1006:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:476:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:998:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb
```

The installation still works, not sure if anything important in the post-install script is skipped. (In prior builds not all plugins were installed because of this, but that seems to have been fixed.)

**Comment by fjperini** [comment]
Yes, it seems that the link was created when creating the bottle, it should not be like that, since they are indicated in postinstall.

In the next version I will have them generated before postinstall.

Do not worry about that warning, it should work fine.

or you can reinstall, uninstalling previously `qgis-res` and doing then:
```
brew install qgis
```

**Comment by fjperini** [comment]
Thanks for the warning, I'll keep it in mind for the next release. We can close this issue.

**Comment by Wicky2k8** [comment]
Thank you!
