### ISSUE TITLE
Brew install qgis fails

### ISSUE THREAD

**Issue by melhaz4** [OSGeo/homebrew-osgeo4mac#952]
While running this command, I continue to get failures with the response below. I think I have all my prerequisites installed.

Command:
`brew install qgis`

Error:
```==> cmake --build . --target all -- -j 4
Last 15 lines from /Users/melanie.hazeley/Library/Logs/Homebrew/qgis/08.cmake:
      QgsPythonUtilsImpl::PyObjectToQString(_object*) in qgspythonutilsimpl.cpp.o
  "_Py_Initialize", referenced from:
      QgsPythonUtilsImpl::init() in qgspythonutilsimpl.cpp.o
      QgsPythonUtilsImpl::initPython(QgisInterface*) in qgspythonutilsimpl.cpp.o
      QgsPythonUtilsImpl::initServerPython(QgsServerInterface*) in qgspythonutilsimpl.cpp.o
  "__Py_NoneStruct", referenced from:
      QgsPythonUtilsImpl::getTraceback() in qgspythonutilsimpl.cpp.o
      QgsPythonUtilsImpl::PyObjectToQString(_object*) in qgspythonutilsimpl.cpp.o
      QgsPythonUtilsImpl::getError(QString&, QString&) in qgspythonutilsimpl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[4347/5440] cd /tmp/qgis-20190319-4264-1w3vdor/QGIS-aff4f23559bc24a6979d35d02b11995a2d4f6bac/build/src/customwidgets && /usr/local/opt/qt/bin/moc @/tmp/qgis-20190319-4264-1w3vdor/QGIS-aff4f23559bc24a6979d35d02b11995a2d4f6bac/build/src/customwidgets/moc_qgsdatetimeeditplugin.cpp_parameters
[4348/5440] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DRENDER_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GAMEPAD_LIB -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSIP_VERSION=0x041308 -DWITH_BINDINGS -DWITH_QTWEBKIT -Dqgis_3d_EXPORTS -I. -I../src/3d -I../src/3d/chunks -I../src/3d/symbols -I../src/3d/terrain -I../src/core -I../src/core/geometry -I../src/core/raster -I../src/core/mesh -I../src/core/symbology -I../src/core/metadata -I../src/core/expression -I../src/core/layout -I../src/core/3d -Isrc/core -Isrc/3d -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/osgeo-gdal/include -isystem /usr/local/opt/sqlite/include -isystem /usr/local/opt/qt/lib/cmake/Qt53DExtras -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/Qt3DCore.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DRender.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DInput.framework/Headers -isystem /usr/local/opt/qt/lib/QtGamepad.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DLogic.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DExtras.framework/Headers -isystem /usr/local/opt/qt/lib/QtMacExtras.framework/Headers -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/osgeo-qt-webkit/include -isystem /usr/local/opt/osgeo-qt-webkit/include/QtWebKitWidgets -isystem /usr/local/opt/osgeo-qt-webkit/include/QtWebKit -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtSerialPort.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -Wno-deprecated-declarations -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC -fvisibility=hidden   -fPIC -std=gnu++11 -MD -MT src/3d/CMakeFiles/qgis_3d.dir/terrain/moc_qgsterraintextureimage_p.cpp.o -MF src/3d/CMakeFiles/qgis_3d.dir/terrain/moc_qgsterraintextureimage_p.cpp.o.d -o src/3d/CMakeFiles/qgis_3d.dir/terrain/moc_qgsterraintextureimage_p.cpp.o -c src/3d/terrain/moc_qgsterraintextureimage_p.cpp
[4349/5440] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DRENDER_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GAMEPAD_LIB -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSIP_VERSION=0x041308 -DWITH_BINDINGS -DWITH_QTWEBKIT -Dqgis_3d_EXPORTS -I. -I../src/3d -I../src/3d/chunks -I../src/3d/symbols -I../src/3d/terrain -I../src/core -I../src/core/geometry -I../src/core/raster -I../src/core/mesh -I../src/core/symbology -I../src/core/metadata -I../src/core/expression -I../src/core/layout -I../src/core/3d -Isrc/core -Isrc/3d -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/osgeo-gdal/include -isystem /usr/local/opt/sqlite/include -isystem /usr/local/opt/qt/lib/cmake/Qt53DExtras -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/Qt3DCore.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DRender.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DInput.framework/Headers -isystem /usr/local/opt/qt/lib/QtGamepad.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DLogic.framework/Headers -isystem /usr/local/opt/qt/lib/Qt3DExtras.framework/Headers -isystem /usr/local/opt/qt/lib/QtMacExtras.framework/Headers -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/osgeo-qt-webkit/include -isystem /usr/local/opt/osgeo-qt-webkit/include/QtWebKitWidgets -isystem /usr/local/opt/osgeo-qt-webkit/include/QtWebKit -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtSerialPort.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -Wno-deprecated-declarations -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC -fvisibility=hidden   -fPIC -std=gnu++11 -MD -MT src/3d/CMakeFiles/qgis_3d.dir/terrain/moc_qgsterraintileloader_p.cpp.o -MF src/3d/CMakeFiles/qgis_3d.dir/terrain/moc_qgsterraintileloader_p.cpp.o.d -o src/3d/CMakeFiles/qgis_3d.dir/terrain/moc_qgsterraintileloader_p.cpp.o -c src/3d/terrain/moc_qgsterraintileloader_p.cpp
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

These open issues may also help:
qgis: can't connect to MS SQL https://github.com/OSGeo/homebrew-osgeo4mac/issues/691
```

**Comment by fjperini** [comment]
We are in a process of reviewing all the formulas and renaming them. It will conclude in a few hours.

It may be related to this. Although, from what I see is a problem already reported several times when the dependencies are not well linked.

https://osgeo.github.io/homebrew-osgeo4mac/docs/installing-QGIS-3/

Wait a couple of hours, we will inform when everything is ready.

Sorry for the inconvenience!

**Comment by melhaz4** [comment]
@fjperini will do!

**Comment by melhaz4** [comment]
FYI @fjperini  this is still failing for me

**Comment by fjperini** [comment]
@melhaz4 in the course of the day I will complete the work we are doing in the repo.


Meanwhile you can do: `brew gist-logs qgis`

To see in more detail what is happening to you.

**Comment by melhaz4** [comment]
@fjperini Here's my output from `brew gist-logs qgis`:
https://gist.github.com/melhaz4/b504c940761aa51f805554fccc3eb594

**Comment by fjperini** [comment]
from what I see, you have another version of Python (from Anaconda and python.org?) installed and the `osgeo-sip` dependency is not linked, among other.

```
-DSIP_MODULE_DIR=/usr/local/opt/osgeo-sip/lib/python3.6/site-packages
-DPYQT5_MOD_DIR=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5
.
.
.
-DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7
```

```
-- Found PythonInterp: /usr/local/opt/python/bin/python3.7 (found suitable version "3.7.2", minimum required is "3") 
-- Found Python executable: /usr/local/opt/python/bin/python3.7
-- Found Python version: 3.7.2
-- Found Python library: 
-- Found Python site-packages: /usr/local/lib/python3.7/site-packages
Traceback (most recent call last):
  File "/tmp/qgis-20190319-18796-1jhdz5p/QGIS-aff4f23559bc24a6979d35d02b11995a2d4f6bac/cmake/FindPyQt5.py", line 34, in <module>
    import PyQt5.pyqtconfig
ModuleNotFoundError: No module named 'PyQt5.pyqtconfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/qgis-20190319-18796-1jhdz5p/QGIS-aff4f23559bc24a6979d35d02b11995a2d4f6bac/cmake/FindPyQt5.py", line 37, in <module>
    import PyQt5.QtCore
ModuleNotFoundError: No module named 'PyQt5.sip'
-- Found SIP version: 4.19.8
-- Found QScintilla2 PyQt module: 2.11.1

```
```
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /anaconda3/bin/icu-config
  /anaconda3/bin/freetype-config
  /anaconda3/bin/xslt-config
  /anaconda3/bin/libpng16-config
  /anaconda3/bin/python3.6m-config
  /anaconda3/bin/libpng-config
  /anaconda3/bin/xml2-config
  /anaconda3/bin/python3-config
  /anaconda3/bin/curl-config
  /anaconda3/bin/ncursesw6-config
  /anaconda3/bin/pcre-config
 /anaconda3/bin/python3.6-config
```

```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  osgeo-insighttoolkit
  gdal
  python
  r
  osgeo-sip
  osgeo-postgis
  openvpn
  qscintilla2
  postgis
  psqlodbc
  r-backup
  openscenegraph-qt5
  osgeo-lastools
  unbound
  pyqt
```


To make sure:

```
$ brew reinstall ninja gsl python qt osgeo-sip osgeo-pyqt osgeo-pyqt-webkit osgeo-qscintilla2 osgeo-postgis osgeo-lastools six bison flex pkg-config
$ brew unlink osgeo-sip osgeo-pyqt osgeo-pyqt-webkit osgeo-qscintilla2 osgeo-postgis osgeo-lastools && brew link osgeo-sip osgeo-pyqt osgeo-pyqt-webkit osgeo-qscintilla2 osgeo-postgis osgeo-lastools --force
$ brew link --overwrite osgeo-pyqt
$ brew unlink gettext python && brew link --force gettext python
```

And retry.

I will try to finish the whole process today! Then you will no longer need to build on your machine.

Remember that you must have your homebrew with all the dependencies correctly linked so that you do not have conflicts with others that you have installed.

**Comment by melhaz4** [comment]
That did it! Thanks for your help! I'll close this ticket and look forward to the new push.

**Comment by fjperini** [comment]
ok, just remember that you will have to link the dependencies well.

**Comment by melhaz4** [comment]
@fjperini another question for you....how can I install QGIS 3.4 instead of 3.6?
